/** @format */

const CSYE_6225 = {
  prerequisites: {
    "Programming Language": ["Java"],

    "Creational Design Patterns": [
      "Singleton",
      "Builder",
      "Prototype",
      "Factory",
      "Abstract Factory",
    ],
    "Structural Design Patterns": [
      "Adapter",
      "Composite",
      "Proxy",
      "Flyweight",
      "Facade",
      "Bridge",
      "Decorator",
    ],
    "Behavioral Design Patterns": [
      "Template Method",
      "Mediator",
      "Chain of Responsibility",
      "Observer",
      "Strategy",
      "Command",
      "State",
      "Visitor",
      "Interpreter",
      "Iterator",
      "Memento",
    ],

    "Object Oriented Programming Concepts": [
      "Encapsulation",
      "Inheritance",
      "Polymorphism",
      "Abstraction",
    ],

    "Java Features": [
      "Procedural",
      "Object-oriented paradigms",
      "Data types",
      "Primitive classes",
      "Wrapper classes",
      "String classes",
      "Abstract classes",
      "Interfaces",
      "Inner classes",
      "Exception handling",
      "Multi-threaded programming",
      "Arrays",
      "Collection framework",
      "Lists",
      "Sets",
      "Maps",
      "File IO",
      "Java Swing",
    ],

    Project: ["Swing application for searching cars"],
    "Testing and Debugging": [
      "Unit Testing",
      "Debugging",
      "Advanced Debugging and Logging",
    ],
    "Java 8 Features": ["Java 8 Features"],

    "User Interfaces": ["Java Swing"],
  },
  course_content: [
    "cloud",
    "DevOps",
    "GitOps",
    "SRE",
    "Linux",
    "Shell Scripting",
    "Version Control with Git",
    "Computer Networking",
    "Cloud Computing",
    "Microservices Architecture",
    "Identity & Access Management",
    "Infrastructure as Code",
    "Cloud Storage Solutions",
    "Continuous Integration, Continuous Delivery, and Continuous Deployment",
    "Operational Visibility (Logging, Metrics, Monitoring, and Alerting)",
    "Load Balancers",
    "Auto-scaling Applications",
    "Event-driven Architecture",
    "Serverless Computing",
    "Securing cloud applications and infrastructure",
    "AWS",
    "Azure",
    "GCP",
    "source",
    "links",
  ],
  AWS: [
    "EC2",
    "S3",
    "Lambda",
    "RDS",
    "DynamoDB",
    "VPC",
    "Route 53",
    "CloudWatch",
    "IAM",
    "Cognito",
    "SES",
    "SNS",
    "SQS",
    "Elastic Beanstalk",
    "Kinesis",
  ],
  Azure: [
    "Virtual Machines",
    "App Service",
    "SQL Database",
    "Cosmos DB",
    "Active Directory",
    "Azure Functions",
    "Azure Logic Apps",
    "Blob Storage",
    "Azure DevOps",
    "Azure Kubernetes Service",
    "Power BI",
  ],
  GCP: [
    "Compute Engine",
    "Cloud Storage",
    "Cloud SQL",
    "BigQuery",
    "Cloud Functions",
    "Pub/Sub",
    "Cloud Spanner",
    "Cloud Datastore",
    "Cloud Firestore",
    "Cloud Identity",
    "Kubernetes Engine",
  ],
  Scenarios: [
    "Load Balancing",
    "Auto Scaling",
    "Database Migration",
    "Disaster Recovery",
    "Data Backup",
    "Web Hosting",
    "Data Analytics",
    "Machine Learning",
    "Serverless Computing",
    "Continuous Integration",
    "Continuous Deployment",
    "Data Warehousing",
  ],
};

const CSYE_7200 = {};

const INFO_6105 = {};

const INFO_6150 = {};

export { CSYE_6225, CSYE_7200, INFO_6105, INFO_6150 };
