/** @format */

const CSYE_6225 = {
  prerequisites: {
    "Programming Language": ["Java"],

    "Creational Design Patterns": [
      "Singleton",
      "Builder",
      "Prototype",
      "Factory",
      "Abstract Factory",
    ],
    "Structural Design Patterns": [
      "Adapter",
      "Composite",
      "Proxy",
      "Flyweight",
      "Facade",
      "Bridge",
      "Decorator",
    ],
    "Behavioral Design Patterns": [
      "Template Method",
      "Mediator",
      "Chain of Responsibility",
      "Observer",
      "Strategy",
      "Command",
      "State",
      "Visitor",
      "Interpreter",
      "Iterator",
      "Memento",
    ],

    "Object Oriented Programming Concepts": [
      "Encapsulation",
      "Inheritance",
      "Polymorphism",
      "Abstraction",
    ],

    "Java Features": [
      "Procedural",
      "Object-oriented paradigms",
      "Data types",
      "Primitive classes",
      "Wrapper classes",
      "String classes",
      "Abstract classes",
      "Interfaces",
      "Inner classes",
      "Exception handling",
      "Multi-threaded programming",
      "Arrays",
      "Collection framework",
      "Lists",
      "Sets",
      "Maps",
      "File IO",
      "Java Swing",
    ],

    Project: ["Swing application for searching cars"],
    "Testing and Debugging": [
      "Unit Testing",
      "Debugging",
      "Advanced Debugging and Logging",
    ],
    "Java 8 Features": ["Java 8 Features"],

    "User Interfaces": ["Java Swing"],
  },
  course_content: [
    "cloud",
    "DevOps",
    "GitOps",
    "SRE",
    "Linux",
    "Shell Scripting",
    "Version Control with Git",
    "Computer Networking",
    "Cloud Computing",
    "Microservices Architecture",
    "Identity & Access Management",
    "Infrastructure as Code",
    "Cloud Storage Solutions",
    "Continuous Integration, Continuous Delivery, and Continuous Deployment",
    "Operational Visibility (Logging, Metrics, Monitoring, and Alerting)",
    "Load Balancers",
    "Auto-scaling Applications",
    "Event-driven Architecture",
    "Serverless Computing",
    "Securing cloud applications and infrastructure",
    "AWS",
    "Azure",
    "GCP",
    "source",
    "links",
  ],
  AWS: [
    "EC2",
    "S3",
    "Lambda",
    "RDS",
    "DynamoDB",
    "VPC",
    "Route 53",
    "CloudWatch",
    "IAM",
    "Cognito",
    "SES",
    "SNS",
    "SQS",
    "Elastic Beanstalk",
    "Kinesis",
  ],
  Azure: [
    "Virtual Machines",
    "App Service",
    "SQL Database",
    "Cosmos DB",
    "Active Directory",
    "Azure Functions",
    "Azure Logic Apps",
    "Blob Storage",
    "Azure DevOps",
    "Azure Kubernetes Service",
    "Power BI",
  ],
  GCP: [
    "Compute Engine",
    "Cloud Storage",
    "Cloud SQL",
    "BigQuery",
    "Cloud Functions",
    "Pub/Sub",
    "Cloud Spanner",
    "Cloud Datastore",
    "Cloud Firestore",
    "Cloud Identity",
    "Kubernetes Engine",
  ],
  Scenarios: [
    "Load Balancing",
    "Auto Scaling",
    "Database Migration",
    "Disaster Recovery",
    "Data Backup",
    "Web Hosting",
    "Data Analytics",
    "Machine Learning",
    "Serverless Computing",
    "Continuous Integration",
    "Continuous Deployment",
    "Data Warehousing",
  ],
};

const CSYE_7200 = {
  keyTerms: [
    "CSYE 7200",
    "Big Data System Engineering",
    "Scala",
    "Term and Year",
    "Credit Hour",
    "Course Format",
    "Instructor Information",
    "Full Name",
    "Email Address",
    "Course Prerequisites",
    "Course Description",
    "Functional Programming",
    "Java virtual machine",
    "Open-source",
    "Programming in Scala",
    "Functional Programming in Scala",
    "Spark",
    "Map/Reduce",
    "Java",
    "Python",
    "R",
    "SQL",
    "ETL",
    "Type-safety",
    "Concurrent Programming",
    "Side Effects",
    "Mutable State",
    "Mathematics",
    "Machine Learning",
    "Grading Breakdown",
    "Project Information",
    "Big Data",
    "Streaming",
    "Databricks Notebook",
    "Reactive System",
    "Unit Tests",
    "Scalability",
    "Course Schedule",
    "Weeks",
    "Parallel Processing",
    "Mutable State",
    "Lazy Functions",
    "Lists",
    "Streams",
    "Generics",
    "Variance",
    "Exceptional Conditions",
    "Functional Composition",
    "For Comprehensions",
    "Recursion",
    "Syntax",
    "Type Declarations",
    "Implicits",
    "Serialization",
    "Deserialization",
    "Futures",
    "Monoids",
    "Functors",
    "Monads",
    "Mid-term exam",
    "Syntactic sugar",
    "Enumerated Types",
    "Actors",
    "Pattern Matching",
    "API",
    "Parsing",
    "DSLs",
    "Spark details",
    "GraphX",
    "MLlib",
    "Spark Streaming",
    "Spark SQL",
    "Play/Activator",
    "Numerical Computing",
    "Projects",
    "Project presentations",
    "Final exam",
    "End-of-Course Evaluation Surveys",
    "Academic Integrity",
    "Rehabilitation Act",
    "Americans with Disabilities Act Amendments Act",
    "Disability Resource Center",
    "Library Services",
    "Blackboard Technical Help",
    "Information Technology Services",
    "Diversity and Inclusion",
    "Title IX",
    "Education Amendments of 1972",
    "Sexual Harassment",
    "Sexual Assault",
    "Relationship Violence",
    "Domestic Violence",
    "Stalking",
    "Title IX Policy",
    "Prohibited Offenses",
  ],
};

const INFO_6105 = {
  keyTerms: [
    "INFO 6105",
    "Data Science Engineering Methods and Tools",
    "Summer 2022",
    "Credit Hour",
    "Online",
    "Instructor Information",
    "Full Name",
    "Email Address",
    "Course Prerequisites",
    "CSYE 6200",
    "INFO 5100",
    "Graduate Level",
    "Undergraduate Level",
    "Machine Learning",
    "Data Science Engineering",
    "Machine Learning Algorithms",
    "Implementation",
    "Evaluation",
    "Best Practices",
    "Learning Models",
    "Complex Data Pipelines",
    "Supervised Learning",
    "Parametric Algorithms",
    "Nonparametric Algorithms",
    "Support Vector Machines",
    "Kernels",
    "Neural Networks",
    "Deep Learning",
    "Unsupervised Learning",
    "Clustering",
    "Dimensionality Reduction",
    "Recommender Systems",
    "Python",
    "Data Preprocessing",
    "Feature Engineering",
    "Data Quality",
    "Data Preparation",
    "Missing Values",
    "Outliers",
    "Data Transformation",
    "Linear Regression",
    "Logistic Regression",
    "Linear Classifiers",
    "Bayesian Classifiers",
    "Histograms Classifiers",
    "Naïve Bayes",
    "Probability Density Functions",
    "K-nearest Neighbor Algorithm",
    "Decision Tree",
    "Ensemble Methods",
    "Random Forest",
    "Feature Selection",
    "Dimension Reduction",
    "Covariance Matrix",
    "Principal Component Analysis",
    "Regularization",
    "Performance Evaluation",
    "Model Performance",
    "Classifier Performance Evaluation",
    "Accuracy",
    "Sensitivity",
    "Specificity",
    "Positive Predictive Value",
    "Receiver Operating Characteristic",
    "Cross Validation",
    "Machine Learning Guidance",
    "Project Presentation",
    "Neural Networks",
    "Deep Learning",
    "End-of-Course Evaluation Surveys",
    "Academic Integrity",
    "Rehabilitation Act",
    "Americans with Disabilities Act Amendments Act",
    "Disability Resource Center",
    "Library Services",
    "Blackboard Technical Help",
    "Information Technology Services",
    "Diversity and Inclusion",
    "Title IX",
    "Education Amendments of 1972",
    "Sexual Harassment",
    "Sexual Assault",
    "Relationship Violence",
    "Domestic Violence",
    "Stalking",
    "Prohibited Offenses",
  ],
};

const INFO_6150 = {
  keyTerms: [
    "INFO 6150",
    "Web Design and User Experience Engineering",
    "Spring 2022",
    "Credit Hour",
    "On-Ground",
    "Office Hours",
    "Instructor Information",
    "Full Name",
    "Email Address",
    "Course Prerequisites",
    "INFO 5100",
    "CSYE 6200",
    "User Experience Design",
    "Web Standards",
    "Best Practices",
    "Information Architecture",
    "Usability",
    "Marketing Hierarchy",
    "Contextual Websites",
    "Value-Driven Websites",
    "Typography",
    "Color Theory",
    "Composition",
    "Responsive Design",
    "CSS3",
    "Basic Scripting",
    "JavaScript Libraries",
    "Static Website",
    "Mobile-First Design",
    "Semantic HTML",
    "Accessibility",
    "Interactive Elements",
    "User Interface",
    "User Experience",
    "CSS Management",
    "Git",
    "Github",
    "Slack",
    "Canvas Learning Management System",
    "Midterm Project",
    "Final Project",
    "Participation",
    "Assignments",
    "Quizzes",
    "End-of-Course Evaluation Surveys",
    "Academic Integrity",
    "Rehabilitation Act",
    "Americans with Disabilities Act Amendments Act",
    "Disability Resource Center",
    "Library Services",
    "Canvas Technical Help",
    "Information Technology Services",
    "Diversity and Inclusion",
    "Title IX",
    "Education Amendments of 1972",
    "Sexual Harassment",
    "Sexual Assault",
    "Relationship Violence",
    "Domestic Violence",
    "Stalking",
    "Prohibited Offenses",
  ],
};

export { CSYE_6225, CSYE_7200, INFO_6105, INFO_6150 };
